parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: ahmadiyya
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: changethis
