AhmadiyyaApplicationBundle:
    resource: "@AhmadiyyaApplicationBundle/Resources/config/routing.xml"
    prefix:   /

AhmadiyyaTajneedBundle:
    resource: "@AhmadiyyaTajneedBundle/Resources/config/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
